### ISSUE TITLE
Documentation: working with record links

### ISSUE THREAD

**Issue by Nickersoft** [surrealdb/surrealdb.go#103]
### Description

I'm not sure if this is an issue shared across all SurrealDB SDKs right now due to how the underlying RPC works, but I'm currently trying to create new records using `db.Create` and passing an array of model IDs as strings inside my interface. However, it doesn't appear that these relations are getting saved in the database, despite the other fields in my interface being stored. My table is schemafull and configured to have the specific column be of type `set<record>`.

Is working with relations not currently supported, or is just currently missing from the docs? If you should be able to create relations via string arrays, happy to open a bug report instead.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ElecTwix** [comment]
Golang SDK does not support bulk creation such as array but it is planned to have.

**Comment by Nickersoft** [comment]
Hey @ElecTwix! Thanks for the quick response – to clarify, I'm not trying to create records in bulk, just store an array of record links as a column on one of my tables. My example repo is a bit complex ATM, and I'd need to carve out time to create an MVP. 

That said, the general steps I'd follow to reproduce are:

1. Using either SurrealQL or a GUI like Surrealist (what I used), create a schemafull table (e.g. "table1") that has a column of type `set<record>`
2. Create another table (e.g. "table2") that stores some data for the new column to reference
3. Using the SDK, attempt to create a new table row that references the `test` table:

```go
db.Create("table1", map[string]interface{}{
  "links": []string{"table2:1234"}
}
```

This is effectively the approach I'm trying, except the query passes but `links` would still be `[]` in the database.

**Comment by Nickersoft** [comment]
Hey @ElecTwix,

Sorry for the delay – just got around to looking at this. I did a bit more digging and it looks like it's a [bug](https://github.com/surrealdb/surrealdb/issues/2881) with SurrealDB and schemafull tables. If I make my table schemaless it works as expected, despite the record links being stored as an array of strings. I can still use the dot notation to reference nested fields when selecting like you can with record links. Going to close this, as I'm tracking it on the main repo now. Thanks for all the help!
