### ISSUE TITLE
surrealdb Auth undefined

### ISSUE THREAD

**Issue by mvestnik** [surrealdb/surrealdb.go#123]
### Describe the bug

Example in Readme incorrect. 
Driver is not idiomatic for Go. 
context.Context is not passed in the request. 
Before you write something - study good examples  of drivers (example: go-redis) and don't embarrass yourself

### Steps to reproduce

Run example in readme

### Expected behaviour

. 

### SurrealDB version

1.1.0

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ElecTwix** [comment]
> Example in Readme incorrect.

Readme is updated according to the main branch, not for release.
If you like to use the latest release please checkout the official [doc](https://docs.surrealdb.com/docs/integration/sdks/golang)

> Driver is not idiomatic for Go.
> context.Context is not passed in the request.

This driver was created when surrealdb in beta and is still improving
If you want to change this please submit a pull request.

> Before you write something - study good examples of drivers (example: go-redis) and don't embarrass yourself

Open source thrives on community collaboration. If you have suggestions for improvement, consider submitting a pull request.
