### ISSUE TITLE
Bug: relate timeout

### ISSUE THREAD

**Issue by wokito** [surrealdb/surrealdb.go#148]
### Describe the bug

When I use the SDK of Go to execute the RELATE on version 2.0 of DB. Timeout will occur. But version 1.53 can be used normally. The error message is as follows:
sending request failed for method 'query': timeout"

### Steps to reproduce

use the SDK of Go to execute the RELATE on version 2.0 of DB.

### Expected behaviour

timeout

### SurrealDB version

2.0.1

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jinrenjie** [comment]
When I upgraded SurrealDB to 2.0.1, I encountered the same situation. I always timed out when creating records. The error was: `sending request failed for method 'create': timeout`.

**Comment by bidamat** [comment]
I get this error: `sending request failed for method 'query': timeout`

**Comment by HilkopterBob** [comment]
Error:
`panic: sending request failed for method 'create': timeout`

Code:
```go 

UserInsertionData, err := db.DB.Create("user", NewUser)
	if err != nil {
		panic(err)
	}
```

Newest SDK commit && surreal 2.0.2 on arch linux

**Comment by HilkopterBob** [comment]
@ElecTwix any updates?

**Comment by ElecTwix** [comment]
> @ElecTwix any updates?

@HilkopterBob, please ask @remade; I didn't change anything.
