### ISSUE TITLE
Bug: Readme example has errors in it

### ISSUE THREAD

**Issue by nickchomey** [surrealdb/surrealdb.go#155]
### Describe the bug

When I run the readme code, it creates distinct columns depending on whether the person is created with `map[interface{}]interface{}{}` or the `Person` struct.

![image](https://github.com/user-attachments/assets/e06a76eb-25e5-4d11-9edd-7af01c77c59e)

I changed the code so that it creates Jane Doe for the Person Struct, and it makes the columns lowercase because of the JSON annotations. 

Should the `map[interface{}]interface{}{}` use lowercase for the fieldnames, like this

```
person1, err := surrealdb.Create[Person](db, models.Table("persons"), map[interface{}]interface{}{
		"name":     "John",
		"surname":  "Doe",
		"location": models.NewGeometryPoint(-0.11, 22.00),
	})
```

Or should the Person struct use uppercase in the json annotations?

Or should the sdk hande all of this automatically (perhaps automatically making all field names lowercase)?

### Steps to reproduce

Run the readme code

### Expected behaviour

That the two methods would use the same columns

### SurrealDB version

latest

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by remade** [comment]
Hi @nickchomey 
This is a go related issue. The field names are dependent on the input. For struct types, with no JSON or CBOR tags, the column name will be the Field name else it will be the name on the tag. For example `surrealdb.Auth` has fields Username and Password; while the backend expects `user` and `pass` instead. If those fields weren't tagged, that would have been an invalid request.
It is best to leave the implementation to users
