### ISSUE TITLE
Empty response on "select"

### ISSUE THREAD

**Issue by jareer12** [surrealdb/surrealdb.go#16]
```go
func get_configs() Config {
	configs := Config{
		user:   "root",
		pass:   "root",
		db:     "test",
		ns:     "test",
		host:   "127.0.0.1",
		scheme: "ws",
		port:   8000,
	}

	return configs
}

func main() {
	_, use_err := db.Use(configs.ns, configs.db)
	data, d_err := db.Select("apps")
	if d_err != nil {
		fmt.Print(d_err)
	}

	fmt.Println(data)

	var apps Results
	json.Unmarshal([]byte(fmt.Sprint(data)), &apps)

	fmt.Println(&apps)

	for i, s := range apps.result {
		fmt.Println(i, s)
	}
}
```

Data appears in the shell but doesn't when fetched from the GoLang SDK.
![image](https://user-images.githubusercontent.com/57962439/191995697-daf81d15-a271-493f-b592-dc97708cd219.png)
![image](https://user-images.githubusercontent.com/57962439/191996192-6febe687-444c-43ea-94a5-a64bae8b0e19.png)

**Comment by iKaio** [comment]
the data `db.Select` returns is already the `result` property that you are looking for.

**Comment by jareer12** [comment]
> the data `db.Select` returns is already the `result` property that you are looking for.

I don't understand what you're talking about but both `data` and `d_err` are empty.

**Comment by jareer12** [comment]
> the data `db.Select` returns is already the `result` property that you are looking for.

How do I access the `result` property.

**Comment by jareer12** [comment]
.

**Comment by garrison-henkle** [comment]
Try:
```
data, d_err := db.Select("apps")
if d_err != nil {
	fmt.Print(d_err)
}

var apps Results
err := surrealdb.Unmarshal(data, &apps)
```
The `surrealdb.Unmarshal()` function takes the `interface{}` return of `db.Select()`, `db.Update()`, etc. `db.Query()` works the same way, just replace `surrealdb.Unmarshal()` with `surrealdb.UnmarshalRaw()`.

`data` is the `result` property from the the jsons you have in the terminal, it is just a nested mess of `[]interface{}` and `map[string]interface{}` in Go that the unmarshal functions will unravel for you.

**Comment by jareer12** [comment]
> The `surrealdb.Unmarshal()` function takes the `interface{}` return of `db.Select()`, `db.Update()`, etc. `db.Query()` works the same way, just replace `surrealdb.Unmarshal()` with `surrealdb.UnmarshalRaw()`.

```shell
.\main.go:85:17: undefined: surrealdb.Unmarshal
```

**Comment by garrison-henkle** [comment]
Oh I just checked and that v0.1.1 tag is several weeks old, while the unmarshal changes were made a few days ago. Someone with access to the repo needs to make a new tag.

To get the new version you'll have to make a new fork, tag it, and then import that version instead. If you don't want to do that yourself, the [newest tag on my repo](https://github.com/garrison-henkle/surrealdb.go/releases/tag/v1.0.3) contains the changes. It does have an additional workaround for a non-driver bug, though, so you'll have to do it yourself if you don't want that. The fix just disables encoding of `<` and `>` to utf8 to allow for `<`, `>`, `<-` and `->` operators to be used, so it is actually better than the official version if anything.

**Comment by jareer12** [comment]
> Oh I just checked and that v0.1.1 tag is several weeks old, while the unmarshal changes were made a few days ago. Someone with access to the repo needs to make a new tag.

```golang
package main

import (
	"fmt"
	"net/http"

	surreal "github.com/garrison-henkle/surrealdb.go"
)

type Config struct {
	ns     string
	db     string
	user   string
	scheme string
	pass   string
	host   string
	port   int
}

type Application struct {
	external_port int16
	host          string
	id            string
	internal_port int
	name          string
	scheme        string
	server_names  []string
}

type Results struct {
	ID     interface{}   `json:"id" msgpack:"id"`
	Result []interface{} `json:"result" msgpack:"result"`
}

func get_configs() Config {
	configs := Config{
		user:   "root",
		pass:   "root",
		db:     "test",
		ns:     "test",
		host:   "127.0.0.1",
		scheme: "ws",
		port:   8000,
	}

	return configs
}

func restart(w http.ResponseWriter, req *http.Request) {
	configs := get_configs()

	url := configs.scheme + "://" + configs.host + ":" + fmt.Sprint(configs.port)

	db, db_err := surreal.New(url + "/rpc")

	if db_err != nil {
		fmt.Print(db_err)
	}

	_, use_err := db.Use(configs.ns, configs.db)
	if use_err != nil {
		fmt.Print(use_err)
	}

	data, d_err := db.Select("apps")
	if d_err != nil {
		fmt.Print(d_err)
	}

	fmt.Println(data)

	var apps Results
	err := surreal.Unmarshal(data, &apps)

	if err != nil {
		fmt.Print(d_err)
	}

	fmt.Println(apps.Result)

	for i, s := range apps.Result {
		fmt.Println(i, s)
	}
}

func main() {
	http.HandleFunc("/restart", restart)
	http.ListenAndServe(":1000", nil)
}
```

I used your repo. same response, same results.

**Comment by garrison-henkle** [comment]
You need to call `db.Signin` before `db.Use`. `var apps Results` should also be `var apps Application` and `Application` needs both its fields exported and `json` tags.

**Comment by jareer12** [comment]
> You need to call `db.Signin` before `db.Use`. `var apps Results` should also be `var apps Application` and `Application` needs both its fields exported and `json` tags.

What json tags does it need?

**Comment by garrison-henkle** [comment]
Basically `Application` needs to be something like this:
```
type Application struct {
	External_port int16    `json:"external_port"`
	Host          string   `json:"host"`
	Id            string   `json:"id"`
	Internal_port int      `json:"internal_port"`
	Name          string   `json:"name"`
	Scheme        string   `json:"scheme"`
	Server_names  []string `json:"server_names"`
}
```

The field names need to be capitalized so they can be exported (the json marshaller can't use non-exported fields), so the json meta data tags allow you to change the name to whatever your actual data looks like. I just used whatever my IDE autofilled above, so you may need to change them to match the case and format of the field names.

**Comment by jareer12** [comment]
> Basically `Application` needs to be something like this:
> 
> ```
> type Application struct {
> 	External_port int16    `json:"external_port"`
> 	Host          string   `json:"host"`
> 	Id            string   `json:"id"`
> 	Internal_port int      `json:"internal_port"`
> 	Name          string   `json:"name"`
> 	Scheme        string   `json:"scheme"`
> 	Server_names  []string `json:"server_names"`
> }
> ```

Doesn't work, still same results

**Comment by garrison-henkle** [comment]
I took your code from above and made it work on my local machine: https://gist.github.com/garrison-henkle/0687a49b1e2e910bbd0c16816a164e10

**Comment by jareer12** [comment]
> I took your code from above and made it work on my local machine: https://gist.github.com/garrison-henkle/0687a49b1e2e910bbd0c16816a164e10
> 
> I created one record as a test:
> 
> ```
> create apps:test1 set host = "google.com"
> [{"time":"4.254208ms","status":"OK","result":[{"host":"google.com","id":"apps:test1"}]}]
> ```
> 
> And got:
> 
> ```
>  [{0 google.com  0   []}]
> ```
> 
> Just add the json tags and export the rest of the fields of Application and it will work.

I'm waiting for the official Golang docs to come out.

**Comment by spit4520** [comment]
> 

Thank you :partying_face: your tag is very helpful, ran into the same issues with Select; the read me at a bare minimum needs to be updated ASAP to fix minor acid traps so people can get started quickly. Nothing exhaustive, just "hey do this, that, this works, this doesn't, generally do this, this common error means this" as opposed to taking apart the Node and Python libraries and docs by hand to figure out whats going on

**Comment by nxy7** [comment]
In case anyone wants to use the latest changes in the repo (like surrealdb.Unmarchal) you can also download module as
`go get github.com/surrealdb/surrealdb.go@main`. 
Select doesn't work for me, I can create stuff, but for some reason select returns empty array. I don't even think it's an issue with unmarchaling because during debugging response from 'select' seems to be empty.
<img width="236" alt="image" src="https://user-images.githubusercontent.com/32909532/220494912-03169fed-f62e-4b83-94d1-1af888fd5514.png">

**Comment by nxy7** [comment]
Nevermind, select does work but I was using it as 
`db.Select("select ticker, name from stock")`
instead of
`db.Select("stock")`
Still figuring out how to filter results, but it should be easy now :P
