### ISSUE TITLE
Bug: Unmarshalling CBOR record ID expects `string` when it could be `any`

### ISSUE THREAD

**Issue by TheRangiCrew** [surrealdb/surrealdb.go#166]
### Describe the bug

When querying a record with an ID that is not a string, such as an array or object, the CBOR unmarshal panics since it expects ID to be a `string`.

Example:
Record uses ID `product:['AAGAAK', d'2024-10-28T22:46:45Z', 0]`

Go panics:
```
panic: interface conversion: interface {} is []interface {}, not string

goroutine 116 [running]:
github.com/surrealdb/surrealdb.go/pkg/models.(*RecordID).UnmarshalCBOR(0xc00049a340, {0xc00074a740, 0x1b, 0x340})
        ~/go/pkg/mod/github.com/surrealdb/surrealdb.go@v1.0.0-beta/pkg/models/record_id.go:53 +0x150
```

### Steps to reproduce

Query a record with a record ID that cannot be a string such as an array or object. When receiving the object the unmarshal will fail.

### Expected behaviour

Since a RecordID is already expecting any for the ID, allow any value to be unmarshalled to any.

### SurrealDB version

2.0.4 for linux on x86_64

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by remade** [comment]
@TheRangiCrew Thanks for the PR
