### ISSUE TITLE
Bug: Strings can't contain the letters "<" and ">".

### ISSUE THREAD

**Issue by 1e99** [surrealdb/surrealdb.go#173]
### Describe the bug

When I try to create a record using either `db.Create()` or `db.Query("CREATE product ....");`, the database times out whenever a string contains the letter `<` and `>`.

### Steps to reproduce

1. Start SurrealDB with this command: `surreal start --user root --pass root --log debug memory`.
2. Create a go file called `main.go`, with the following content:
```go
package main

import (
	"log"

	"github.com/surrealdb/surrealdb.go"
)

func main() {
	// surreal start --user root --pass root memory
	db, err := surrealdb.New("ws://localhost:8000/rpc")
	if err != nil {
		log.Fatalf("%s", err)
	}

	_, err = db.Signin(map[string]interface{}{
		"user": "root",
		"pass": "root",
	})
	if err != nil {
		log.Fatalf("%s", err)
	}

	_, err = db.Use("test", "test")
	if err != nil {
		log.Fatalf("%s", err)
	}

	_, err = db.Create("prodct", map[string]any{
		"name": "<",
	})
	if err != nil {
		log.Fatalf("%s", err)
	}
}
```
3. Run the go program. It should log `sending request failed for method 'create': timeout`.

### Expected behaviour

I expect it to create the record instead of timing out

### SurrealDB version

2.0.4 for linux on x86_64

### Contact Details

1e99@1e99.eu

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by remade** [comment]
@1e99 I believe that is a valid surrealQL symbol that will raise an issue

**Comment by 1e99** [comment]
Surrealist can perfectly execute the following statement, and I can perfectly create a record manually in the "Explorer" tab, with the name containing a "<".
```
CREATE product CONTENT {
    name: "<",
};
```

The go SDK can't run that statement too.
```go
package main

import (
	"log"

	"github.com/surrealdb/surrealdb.go"
)

func main() {
	// surreal start --user root --pass root memory
	db, err := surrealdb.New("ws://localhost:8000/rpc")
	if err != nil {
		log.Fatalf("%s", err)
	}

	_, err = db.Signin(map[string]interface{}{
		"user": "root",
		"pass": "root",
	})
	if err != nil {
		log.Fatalf("%s", err)
	}

	_, err = db.Use("test", "test")
	if err != nil {
		log.Fatalf("%s", err)
	}

	_, err = db.Query(
		`CREATE product CONTENT {
    		name: "<",
      	};`,
		nil,
	)
	if err != nil {
		log.Fatalf("%s", err)
	}
}
```

**Comment by 1e99** [comment]
I would like to also mention that go does some pre-processing of strings when using the default `encoding/json` package.

> String values encode as JSON strings coerced to valid UTF-8, replacing invalid bytes with the Unicode replacement rune. So that the JSON will be safe to embed inside HTML <script> tags, the string is encoded using [HTMLEscape](https://pkg.go.dev/encoding/json#HTMLEscape), which replaces "<", ">", "&", U+2028, and U+2029 are escaped to "\u003c","\u003e", "\u0026", "\u2028", and "\u2029". This replacement can be disabled when using an [Encoder](https://pkg.go.dev/encoding/json#Encoder), by calling [Encoder.SetEscapeHTML](https://pkg.go.dev/encoding/json#Encoder.SetEscapeHTML)(false).
[Source](https://pkg.go.dev/encoding/json#Marshal)

A simple showcase is this program:
```go
package main

import (
	"encoding/json"
	"log"
)

func main() {
	test := struct {
		Name string `json:"name"`
	}{
		Name: ">",
	}

	data, err := json.Marshal(&test)
	if err != nil {
		log.Fatalf("%s", err)
	}

	log.Printf("%s", string(data))
}
```

It does NOT output `{"name": ">"}` like you would think, but instead outputs `{"name":"\u003e"}`.

I tried modifying my CREATE query to use this value, adjusting it to this:
```
CREATE product CONTENT {
    name: "\u003e",
};
```

And sure enough, now I can no longer create the record in Surrealist
```
-------- Query 1 --------

'There was a problem with the database: Parse error: Invalid escape character `u`, valid characters are `\\`, `"`, `/`, `b`, `f`, `n`, `r`, or `t`
 --> [2:11]
  |
2 | name: "\\u003e",
  |       ^^^ 
'
```

I am unsure why it times out in the go SDK tho.

**Comment by 1e99** [comment]
I am using `v0.2.1`. I upgraded to the latest commit, and now it does work, thanks!
```go
package main

import (
	"log"

	"github.com/surrealdb/surrealdb.go"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

type Product struct {
	Name string `json:"name"`
}

func main() {
	// surreal start --user root --pass root memory
	db, err := surrealdb.New("ws://localhost:8000/rpc")
	if err != nil {
		log.Fatalf("%s", err)
	}

	token, err := db.SignIn(&surrealdb.Auth{
		Username: "root",
		Password: "root",
	})
	if err != nil {
		log.Fatalf("%s", err)
	}

	err = db.Use("test", "test")
	if err != nil {
		log.Fatalf("%s", err)
	}

	err = db.Authenticate(token)
	if err != nil {
		log.Fatalf("%s", err)
	}

	product, err := surrealdb.Create[Product](db, models.Table("product"), Product{
		Name: ">",
	})
	if err != nil {
		log.Fatalf("%s", err)
	}

	log.Fatalf("%+v", product)
}
```

Just for me, is the API expected to change a lot or is it already pretty stable?
