### ISSUE TITLE
GitHub actions for linting and testing

### ISSUE THREAD

**Issue by EtienneBruines** [surrealdb/surrealdb.go#23]
It'd be nice to automate the testing and linting, to make pull requests validated easier.

These things might be nice to include:
- [ ] `go fmt`
- [ ] `goimports`
- [ ] `go mod tidy`
- [ ] `go mod verify`
- [ ] `go vet`
- [ ] `staticcheck` - see https://staticcheck.io/
- [ ] `gosec` - see https://github.com/securego/gosec
- [ ] `go test`

**Comment by tpotjj** [comment]
Would it be preferable to have pre-commit as well?

**Comment by EtienneBruines** [comment]
Personally I'd say yes - but with Go there's (as far as I know) no predefined way of doing so, so I wouldn't really know. 

But yes, it makes sense that most things the CI/CD would test (like linting) would be part of the pre-commit.

**Comment by EtienneBruines** [comment]
Good catch @ffrizzo !
