### ISSUE TITLE
Might be fair to put some under construction to the repo for now

### ISSUE THREAD

**Issue by clausMeko** [surrealdb/surrealdb.go#39]
I was trying to connect to the Server using the URL that works via curl.

As a result I got the error `malformed ws or wss URL`. Then I noticed this SDK is somehow only for **Websockets**, when I wanted to see how that works the [official docs](https://surrealdb.com/docs/integration/websockets) told me that this is 'The documentation for this integration is coming soon.'

To prevent more users from this unnecessary spend time and inconvenience it might be better to put some disclaimer at the repo.

My code has nothing to do with what i am implying but for completeness:

```go 
package main

import (
	"fmt"

	surreal "github.com/surrealdb/surrealdb.go"
)

func main() {
	db, err := surreal.New("http://localhost:8012/sql")
	if err != nil {
		panic(err)
	}
	t, err := db.Authenticate("root:root")
	if err != nil {
		panic(err)
	}
	fmt.Printf("Authenticate: %s", t)
	res, err := db.Query("CREATE productManager:KlausIker SET firstName = 'Klaus', lastName = 'Iker';", nil)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Query: %s", res)
}

```

**Comment by ElecTwix** [comment]
Hey, I'm using the repo for 1-2 weeks now, with ~100k rows.

I can say most things working ok, yeah there is something with the library that sometimes does not make sense but in the end, it is working ok.

1. You look into [tests](https://github.com/surrealdb/surrealdb.go/blob/main/db_test.go) and understand the lib
2. if that's not enough I can always look into source code tiny compared to other projects.

Also, I wish there was a better readme and doc, it will be better in time but for now.

**Comment by BerndCzech** [comment]
Thank you so much for that hint. If they just would make the tests **Examples** they would appear in the documentation ... 

Really a great hinit - please close.

**Comment by phughk** [comment]
Hey @clausMeko @ElecTwix @BerndCzech , thanks for the info above!

RE: web vs websockets - functionally, they are identical, but with websockets you aren't re-initiating the HTTP connection per request. That's why websockets is prioritised. Plus new functionality like Live Queries only work on websockets.

RE tests -> docs we will fix something around that. Alex has already done the python drivers this way; Happy to do golang and java.

Thanks for highlighting this!
