### ISSUE TITLE
Getting Parsing Error When Use Fetch with map[string]interface

### ISSUE THREAD

**Issue by ElecTwix** [surrealdb/surrealdb.go#40]
Hi Everyone,

I was selecting the record and fetching it is the field record link with the fetch keyword
but when I try to use it with the parameter it gives
 `There was a problem with the database: Parse error when parsing 'fetch $fetchstr'`
this error I checkout the source code [this line](https://github.com/surrealdb/surrealdb.go/blob/main/internal/websocket/ws.go#L112) JSON Marshaling giving the error.
Also, I tried with not safe method string merge ( fmt.sprintf ) and added my string at the end it worked that way.

Am I doing something wrong?
if that's the case please let me know.

The Code I'm trying to fetch

```go
res, err := db.Globaldb.Query("select * from $table fetch $fetchstr;", map[string]interface{}{
	"table":  ID,
	"fetchstr": fetchstr,
})

```

## UPDATE:
for clear out
### The problem I was facing was:
After the FETCH statement, arguments are no longer parsed.
### Example:
`select * from $table FETCH $fetchstr;`
$**table** will parse but $**fetchstr** will not parse

**Comment by phughk** [comment]
Thanks! We will add a test for this.

**Comment by sbshah97** [comment]
Can I take this up as discussed in Slack? Here's how I am looking to do this. 

Step 1: Write a test in `db_test.go` for fetch to ensure fetch works properly.
Step 2: Replicate this particular error in the test case to see if it's currently working
Step 3: Based on Step 2, decide if we need a fix or this is already done and push the test case for fetch as it is.

**Comment by phughk** [comment]
Yes please @sbshah97 ! That is exactly what is needed

**Comment by sbshah97** [comment]
Hi had some work, picking this back up

**Comment by ElecTwix** [comment]
Sorry for delay here to way to reproduce

```go
func (s *SurrealDBTestSuite) TestFetch() {
	userSlice := []testUser{
		{Username: "arthur", Personal: PersonalInfo{Name: "arthur", Surname: "morgan"}, Password: "deer", Friends: []string{"users:john"}},
	}

	for _, v := range userSlice {
		data, err := s.db.Create(v.ID, v)
		s.NoError(err)
		s.NotNil(data)
	}

	for _, v := range userSlice {
		res, err := s.db.Query("select * from $table fetch $fetchstr;", map[string]interface{}{
			"record":   v.ID,
			"fetchstr": "friends.*",
		})
		// it will throw err
		fmt.Println(res, err)
		s.NoError(err)
		s.NotNil(res)
	}
}
```

https://github.com/ElecTwix/surrealdb.go/commit/6af31845c1468940ac902365f7ea0e016cb82677#diff-842765a20a0a937a8eb5267b53fb11b7493cc6c2a6a8871e1da2b684702c5bc9R502

```go
db_test.go:503: 
Error Trace:	/home/electwix/dev/go/surrealdb.go/db_test.go:503
Error:      	Received unexpected error:
sending request failed for method 'query': There was a problem with the database: Parse error: Failed to parse query at line 1 column 28 expected a idiom
1 | select * from $table fetch $fetchstr;
Test:       	TestSurrealDBSuite/gorilla/TestFetch
```

## to reproduce
just clone the repo and run `go test -v`

**Comment by sbshah97** [comment]
What is `v.ID` over here?

**Comment by ElecTwix** [comment]
> What is `v.ID` over here?

came from `testUser`'s ID on `db_test.go`

**Comment by sbshah97** [comment]
From the looks of it issue here seems to be not being able to parse the fetch string. Just want to confirm if we are seeing this in other drivers or not ? 

cc: @timpratim @phughk ? 

If not probably will dive again in on this but from what I could see adding fmt statements till the end of the call stack, the query is being sent as correctly as possible.

**Comment by ElecTwix** [comment]
After reproducing the issue with SurrealQL,
I created an issue on the SurrealDB repo: https://github.com/surrealdb/surrealdb/issues/3028
