### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by agufagit** [surrealdb/surrealdb.go#71]
for query `select * from ->contact->profile;`

I got error: `There was a problem with the database: Parse error on line 1 at character 0 when parsing 'select * from -Ϭontact->profile;'`

somehow `>c` is encoded to `Ϭ`

I ran the same query from thunder client, and it returned fine without error, so it doesn't look like it's a problem with the server

here is [Link to minimal reproduction repo](https://github.com/agufagit/surrealdb-issue)

**Comment by ElecTwix** [comment]
Seems like #62 and fixed in https://github.com/surrealdb/surrealdb/pull/1888
I think in the next release it will be fixed.
