### ISSUE TITLE
Add support for handling diffs (in live query responses)

### ISSUE THREAD

**Issue by phughk** [surrealdb/surrealdb.go#81]
Add support for handling DIFF type responses in live query notifications.

This is different to handling live query notifications, described here: https://github.com/surrealdb/surrealdb.go/issues/80

The notifications from live queries can return either the full document after modification (creation, update, delete), or they may instead send the diff which resembles a git diff to the document.

This ticket is about handling that functionality.

**Comment by phughk** [comment]
Reference protocol implementation in javascript
https://github.com/surrealdb/surrealdb.js/pull/151

**Comment by emilaleksanteri** [comment]
Is this issue still available? Saw that the live queries are addressed #88

**Comment by phughk** [comment]
Hey @emilaleksanteri ! Yes this is still available :) If you would like to take it up, then happy to assign you to the ticket

**Comment by Atoo35** [comment]
Can close this
