### ISSUE TITLE
Example fails in Beta 11 - panic: sending request failed for method 'change': Method not found

### ISSUE THREAD

**Issue by exitexplorer** [surrealdb/surrealdb.go#99]
### Describe the bug

Newbie .....

When executing example code it fails on line 66 with following error:

// Change part/parts of user
changes := map[string]string{"name": "Jane"}
if _, err = db.Change(selectedUser.ID, changes); err != nil {
panic(err)
}

panic: sending request failed for method 'change': Method not found

goroutine 1 [running]:
main.main()
	/home/mjc4/go/src/testsurrealdb/testsurrealdb.go:67 +0xf45

I believe that is because Change has been replaced with Merge and SDK has not been updated.

### Steps to reproduce

Run example code.

### Expected behaviour

Only name is changed on record.

### SurrealDB version

1.0.0-beta.11+20230905.59718fc for linux on x86_64

### Contact Details

webmaster@exitexplorer.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ElecTwix** [comment]
fixed with #98 waiting for SurrealDB's team's review.

**Comment by exitexplorer** [comment]
Sorry I didn't see that.

:(
